spring:
  cloud:    config:      enabled: false
  application:
    name: outh2_WebClient

  security:
    oauth2:
      client:
        provider:
          authProvider:
            token-uri: https://test.api.amadeus.com/v1/security/oauth2/token
        registration:
          authProvider:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials